name: Daily AI Digest

on:
  schedule:
    - cron: "0 4 * * *"   # 9:30 AM IST
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
<<<<<<< HEAD

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI Agent
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
=======
    env:
     NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
     OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
     EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
     EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run Agent
        
>>>>>>> c0e80c362219714906d4592f42522103ad5ea7f9
        run: python -m app.main